# Generated by Django 5.1.2 on 2024-12-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('admissionNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=50)),
                ('studentClass', models.CharField(blank=True, max_length=10, null=True)),
                ('studentDOB', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('aadharNumber', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(blank=True, max_length=50, null=True)),
                ('currentDateTime', models.DateTimeField(auto_now_add=True)),
                ('studentAddress', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('previousSchool', models.CharField(blank=True, max_length=50, null=True)),
                ('previousClass', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualFee', models.IntegerField(default=0)),
                ('januaryFee', models.IntegerField(default=0)),
                ('februaryFee', models.IntegerField(default=0)),
                ('marchFee', models.IntegerField(default=0)),
                ('aprilFee', models.IntegerField(default=0)),
                ('mayFee', models.IntegerField(default=0)),
                ('juneFee', models.IntegerField(default=0)),
                ('julyFee', models.IntegerField(default=0)),
                ('augustFee', models.IntegerField(default=0)),
                ('septemberFee', models.IntegerField(default=0)),
                ('octoberFee', models.IntegerField(default=0)),
                ('novemberFee', models.IntegerField(default=0)),
                ('decemberFee', models.IntegerField(default=0)),
                ('admissionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admission.students')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.BooleanField(default=False)),
                ('januaryFee', models.IntegerField(default=0)),
                ('februaryFee', models.IntegerField(default=0)),
                ('marchFee', models.IntegerField(default=0)),
                ('aprilFee', models.IntegerField(default=0)),
                ('mayFee', models.IntegerField(default=0)),
                ('juneFee', models.IntegerField(default=0)),
                ('julyFee', models.IntegerField(default=0)),
                ('augustFee', models.IntegerField(default=0)),
                ('septemberFee', models.IntegerField(default=0)),
                ('octoberFee', models.IntegerField(default=0)),
                ('novemberFee', models.IntegerField(default=0)),
                ('decemberFee', models.IntegerField(default=0)),
                ('admissionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admission.students')),
            ],
        ),
    ]
